spring.application.name=backend

# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/legal-advisor-e-fir-db
spring.datasource.username=postgres
spring.datasource.password=Postgre@7874
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123

# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.com.legal_advisor_e_fir=DEBUG
